name: bookclub
description: Read books with your friends
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get_it: ^4.0.4
  injectable: ^1.0.2
  auto_route: ^0.6.6
  stacked: ^1.7.5
  stacked_services: ^0.5.0
  stacked_hooks: ^0.1.3
  shared_preferences: ^0.5.8
  observable_ish: ^2.1.4
  http: ^0.12.2
  provider: ^4.3.1
  firebase_auth: ^0.16.1
  reactive_forms: ^2.0.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner: ^1.10.0
  injectable_generator: ^1.0.2
  auto_route_generator: ^0.6.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
